//! ${API_NAME} — graduated MCP server from a workflow-stored API pattern
//!
//! Generated from workflow:api_graduate. Single tool, statically wired
//! to one upstream HTTP API. Reads credentials from environment at runtime.

use anyhow::{Context, Result};
use rmcp::{
    handler::server::{tool::Parameters, ServerHandler},
    model::*,
    schemars::{self, JsonSchema},
    serde_json,
    service::RequestContext,
    tool, tool_handler, tool_router,
    ServiceExt, ErrorData as McpError, RoleServer,
};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

// ─── PATTERN-DERIVED CONSTANTS ────────────────────────────────────────
// These are filled in by workflow:api_graduate at scaffold time.

const API_NAME:        &str = "${API_NAME}";
const API_DESCRIPTION: &str = "${API_DESCRIPTION}";
const URL_PATTERN:     &str = "${URL_PATTERN}";
const METHOD:          &str = "${METHOD}";
const CRED_ENV_VAR:    &str = "${CRED_ENV_VAR_NAME}";
const CRED_HEADER:     &str = "${CRED_HEADER}";
const CRED_PREFIX:     &str = "${CRED_PREFIX}";

// ─── INPUT SCHEMA (auto-derived from pattern placeholders + types) ───
// schemars generates the JSON schema; rmcp surfaces it via list_tools.

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
struct CallArgs {
    // ${INPUT_FIELDS}
}

// ─── HANDLER ─────────────────────────────────────────────────────────

#[derive(Clone)]
struct ApiTool {
    http: reqwest::Client,
    tool_router: rmcp::handler::server::tool::ToolRouter<ApiTool>,
}

#[tool_router]
impl ApiTool {
    fn new() -> Self {
        Self {
            http: reqwest::Client::builder()
                .user_agent(format!("{}/{}", API_NAME, env!("CARGO_PKG_VERSION")))
                .build()
                .expect("reqwest client"),
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = API_DESCRIPTION)]
    async fn call(
        &self,
        Parameters(args): Parameters<CallArgs>,
    ) -> Result<CallToolResult, McpError> {
        // 1. Pull credential from env at call time, not startup.
        let cred = std::env::var(CRED_ENV_VAR).map_err(|_| {
            McpError::invalid_request(
                format!("Missing required env var: {}. Set it before invoking this tool.", CRED_ENV_VAR),
                None,
            )
        })?;

        // 2. Build URL by substituting placeholders from args.
        let url = ${URL_BUILDER_EXPR};

        // 3. Build the request.
        let mut req = self.http.request(METHOD.parse().unwrap(), &url);
        req = req.header(CRED_HEADER, format!("{}{}", CRED_PREFIX, cred));

        // 4. (Optional, generated only if the API has a body template)
        // ${BODY_BUILDER}

        // 5. Dispatch and pass through.
        let resp = req.send().await.map_err(|e| {
            McpError::internal_error(format!("HTTP request failed: {}", e), None)
        })?;

        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();

        if !status.is_success() {
            return Err(McpError::internal_error(
                format!("Upstream returned {}: {}", status, body),
                None,
            ));
        }

        // 6. Try to parse as JSON; fall back to text.
        let content = match serde_json::from_str::<serde_json::Value>(&body) {
            Ok(v) => Content::text(serde_json::to_string_pretty(&v).unwrap_or(body)),
            Err(_) => Content::text(body),
        };

        Ok(CallToolResult::success(vec![content]))
    }
}

#[tool_handler]
impl ServerHandler for ApiTool {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: API_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
            },
            instructions: Some(format!(
                "Standalone MCP server for {}. Requires {} env var. Generated by workflow:api_graduate.",
                API_NAME, CRED_ENV_VAR
            )),
        }
    }
}

// ─── ENTRY POINT ─────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    // Stderr-only logging (stdout is reserved for MCP framing)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();

    let service = ApiTool::new()
        .serve(rmcp::transport::stdio())
        .await
        .context("failed to start MCP service")?;

    service.waiting().await?;
    Ok(())
}
