//! yahoo_chart — graduated MCP server from a workflow-stored API pattern
//!
//! Generated from workflow:api_graduate. Single tool, statically wired
//! to one upstream HTTP API. Credentials read from environment at call time
//! (skipped when CRED_ENV_VAR is empty, e.g. for public APIs).

use anyhow::{Context, Result};
use rmcp::{
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars::{self, JsonSchema},
    serde_json,
    tool, tool_handler, tool_router,
    ErrorData as McpError, ServerHandler, ServiceExt,
};
use serde::{Deserialize, Serialize};

// ─── PATTERN-DERIVED CONSTANTS ────────────────────────────────────────
// Filled in by workflow:api_graduate at scaffold time.

const API_NAME: &str = "yahoo_chart";
const API_DESCRIPTION: &str = "Yahoo Finance chart data";
const URL_PATTERN: &str = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?interval=1d";
const METHOD: &str = "GET";
const CRED_ENV_VAR: &str = ""; // empty = no auth
const CRED_HEADER: &str = "";
const CRED_PREFIX: &str = "";

// ─── INPUT SCHEMA (derived from URL placeholders + body template) ────

#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CallArgs {
    /// Symbol substitution for the URL placeholder.
    pub symbol: String,
}

// ─── HANDLER ─────────────────────────────────────────────────────────

#[derive(Clone)]
pub struct ApiTool {
    http: reqwest::Client,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl ApiTool {
    pub fn new() -> Self {
        Self {
            http: reqwest::Client::builder()
                .user_agent(format!(
                    "{}/{} (Mozilla/5.0)",
                    API_NAME,
                    env!("CARGO_PKG_VERSION")
                ))
                .build()
                .expect("reqwest client"),
            tool_router: Self::tool_router(),
        }
    }

    #[tool(name = "yahoo_chart", description = "Yahoo Finance chart data")]
    pub async fn call_tool(
        &self,
        params: Parameters<CallArgs>,
    ) -> Result<CallToolResult, McpError> {
        let args = params.0;

        // Build URL by substituting placeholders.
        let url = URL_PATTERN.replace("{symbol}", &args.symbol);

        // Build request.
        let mut req = self.http.request(
            METHOD.parse().unwrap_or(reqwest::Method::GET),
            &url,
        );

        // Inject credential ONLY if configured.
        if !CRED_ENV_VAR.is_empty() {
            let cred = std::env::var(CRED_ENV_VAR).map_err(|_| {
                McpError::invalid_request(
                    format!("Missing required env var: {}", CRED_ENV_VAR),
                    None,
                )
            })?;
            req = req.header(CRED_HEADER, format!("{}{}", CRED_PREFIX, cred));
        }

        // Dispatch.
        let resp = req.send().await.map_err(|e| {
            McpError::internal_error(format!("HTTP request failed: {}", e), None)
        })?;

        let status = resp.status();
        let body = resp.text().await.unwrap_or_default();

        if !status.is_success() {
            return Err(McpError::internal_error(
                format!("Upstream returned {}: {}", status, body),
                None,
            ));
        }

        // Pretty-print JSON if possible; fall back to raw text.
        let formatted = match serde_json::from_str::<serde_json::Value>(&body) {
            Ok(v) => serde_json::to_string_pretty(&v).unwrap_or(body),
            Err(_) => body,
        };

        Ok(CallToolResult::success(vec![Content::text(formatted)]))
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for ApiTool {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::V_2024_11_05,
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: Implementation {
                name: API_NAME.to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
                title: None,
                description: Some(API_DESCRIPTION.to_string()),
                icons: None,
                website_url: None,
            },
            instructions: Some(format!(
                "Standalone MCP server for {}. Generated by workflow:api_graduate.",
                API_NAME
            )),
        }
    }
}

// ─── ENTRY POINT ─────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| "info".into()),
        )
        .init();

    let service = ApiTool::new()
        .serve(rmcp::transport::stdio())
        .await
        .context("failed to start MCP service")?;

    service.waiting().await?;
    Ok(())
}
